// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbbndaiwkdxpwanydgvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYm5kYWl3a2R4cHdhbnlkZ3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzU0MTMsImV4cCI6MjA2OTQxMTQxM30.w9URYWC0iTTH5YqtTMxHR5SWh_26Fphq00Hd3djLabY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});